# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e824e2f9b678147b19d79405833ddce5d2b61bce77495402fa35c97b1ef195db2eb68e07119b2ebaa524dcd5a4822a3e0dd62e17b4824d14477ee8e7c887039

test:
  secret_key_base: 06d3747e61771d3ca70bf69fc23533c42ba5015391b9da48960ac8cae1c1d42de9d3d00f8907e9dabe5f54f13c765ff7e35bb842ff01344c6bd35cffa86394ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
